theme = "lanyon-hugo"
baseURL = "/Hippocamplus/"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.RData", "\\.gz$"]
publishDir = "docs"
canonifyurls = true
relativeURLs = true
GoogleAnalytics = "UA-113785126-1"
paginate = 10

[params]
title = "Hippocamplus"
tagline = 'My Second Memory'
description = 'A place to gather useful information I keep on forgetting.'
year = "2019 Jean Monlong"
[params.github]
url = "https://github.com/jmonlong"

[permalinks]
post = "/:year/:month/:day/:slug/"
fixed = ":slug/"
